FROM spark:3.5.1

USER root

WORKDIR /opt/app

COPY target/scala-2.12/lol-streaming-assembly-0.1.0.jar /opt/app/app.jar

RUN curl -L -o /opt/spark/jars/spark-sql-kafka-0-10_2.12-3.5.1.jar \
    https://repo1.maven.org/maven2/org/apache/spark/spark-sql-kafka-0-10_2.12/3.5.1/spark-sql-kafka-0-10_2.12-3.5.1.jar && \
    curl -L -o /opt/spark/jars/kafka-clients-3.5.1.jar \
    https://repo1.maven.org/maven2/org/apache/kafka/kafka-clients/3.5.1/kafka-clients-3.5.1.jar && \
    curl -L -o /opt/spark/jars/spark-token-provider-kafka-0-10_2.12-3.5.1.jar \
    https://repo1.maven.org/maven2/org/apache/spark/spark-token-provider-kafka-0-10_2.12/3.5.1/spark-token-provider-kafka-0-10_2.12-3.5.1.jar

USER 185

ENTRYPOINT ["/opt/spark/bin/spark-submit","--master", "spark://spark-master:7077","--deploy-mode", "client","--class", "consumer.SparkToAzureSql","/opt/app/app.jar"]
