FROM spark:3.5.1

USER root
WORKDIR /opt/app

COPY target/scala-2.12/lol-streaming-assembly-0.1.0.jar /opt/app/app.jar

ENTRYPOINT ["/opt/spark/bin/spark-submit", "--class", "producer.MainApp", "--master", "local[*]", "--packages", "org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.1,org.postgresql:postgresql:42.7.3", "/opt/app/app.jar"]

CMD []
