package producer

class Scoreboard(
  val id: Int,
  val overviewpage: String,
  val name: String,
  val link: String,
  val champion: String,
  val kills: String,
  val deaths: String,
  val assists: String,
  val gold: String,
  val cs: String,
  val damagetochampions: String,
  val items: String,
  val teamkills: String,
  val teamgold: String,
  val team: String,
  val teamvs: String,
  val time: String,
  val playerwin: String,
  val datetime_utc: String,
  val dst: String,
  val tournament: String,
  val role: String,
  val gameid: String,
  val matchid: String,
  val gameteamid: String,
  val gameroleid: String,
  val statspage: String,
  val uniqueline: String,
  val uniquelinevs: String
)
