package producer

class Scoreboard(
  val id: Int,
  val overviewpage: String,
  val name: String,
  val link: String,
  val champion: String,
  val kills: String,
  val deaths: String,
  val assists: String,
  val gold: String,
  val cs: String,
  val damagetochampions: String,
  val items: String,
  val teamkills: String,
  val teamgold: String,
  val team: String,
  val teamvs: String,
  val time: String,
  val playerwin: String,
  val datetime_utc: String,
  val dst: String,
  val tournament: String,
  val role: String,
  val gameid: String,
  val matchid: String,
  val gameteamid: String,
  val gameroleid: String,
  val statspage: String,
  val uniqueline: String,
  val uniquelinevs: String
)

object Scoreboard {
  def apply(
    id: Int,
    overviewpage: String,
    name: String,
    link: String,
    champion: String,
    kills: String,
    deaths: String,
    assists: String,
    gold: String,
    cs: String,
    damagetochampions: String,
    items: String,
    teamkills: String,
    teamgold: String,
    team: String,
    teamvs: String,
    time: String,
    playerwin: String,
    datetime_utc: String,
    dst: String,
    tournament: String,
    role: String,
    gameid: String,
    matchid: String,
    gameteamid: String,
    gameroleid: String,
    statspage: String,
    uniqueline: String,
    uniquelinevs: String
  ): Scoreboard =
    new Scoreboard(
      id,
      overviewpage,
      name,
      link,
      champion,
      kills,
      deaths,
      assists,
      gold,
      cs,
      damagetochampions,
      items,
      teamkills,
      teamgold,
      team,
      teamvs,
      time,
      playerwin,
      datetime_utc,
      dst,
      tournament,
      role,
      gameid,
      matchid,
      gameteamid,
      gameroleid,
      statspage,
      uniqueline,
      uniquelinevs
    )
}
